default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: tamiris
  password: sw9pwC5prRI1vSQr4ezvbg
  host: ringed-pony-16530.j77.aws-us-east-1.cockroachlabs.cloud
  port: 26257
  database: defaultdb
  sslmode: verify-full

test:
  <<: *default
  username: tamiris
  password: sw9pwC5prRI1vSQr4ezvbg
  host: ringed-pony-16530.j77.aws-us-east-1.cockroachlabs.cloud
  port: 26257
  database: defaultdb
  sslmode: verify-full

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: require

# Configurações para Solid Cache, Queue e Cable
cache:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'tamiris' %>
  password: <%= ENV['DB_PASSWORD'] || 'sw9pwC5prRI1vSQr4ezvbg' %>
  host: <%= ENV['DB_HOST'] || 'ringed-pony-16530.j77.aws-us-east-1.cockroachlabs.cloud' %>
  port: <%= ENV['DB_PORT'] || '26257' %>
  database: <%= ENV['DB_NAME'] || 'defaultdb' %>
  sslmode: verify-full

queue:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'tamiris' %>
  password: <%= ENV['DB_PASSWORD'] || 'sw9pwC5prRI1vSQr4ezvbg' %>
  host: <%= ENV['DB_HOST'] || 'ringed-pony-16530.j77.aws-us-east-1.cockroachlabs.cloud' %>
  port: <%= ENV['DB_PORT'] || '26257' %>
  database: <%= ENV['DB_NAME'] || 'defaultdb' %>
  sslmode: verify-full

cable:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'tamiris' %>
  password: <%= ENV['DB_PASSWORD'] || 'sw9pwC5prRI1vSQr4ezvbg' %>
  host: <%= ENV['DB_HOST'] || 'ringed-pony-16530.j77.aws-us-east-1.cockroachlabs.cloud' %>
  port: <%= ENV['DB_PORT'] || '26257' %>
  database: <%= ENV['DB_NAME'] || 'defaultdb' %>
  sslmode: verify-full
