default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: uniquest_development

test:
  <<: *default
  database: uniquest_test

production:
  <<: *default
  database: uniquest_production
  username: root
  password: root
  host: localhost
