default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: tamiris
  password: _PBPzuhMJLiJCf9PiAY8gA
  host: wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud
  port: 26257
  database: defaultdb
  sslmode: verify-full

test:
  <<: *default
  username: tamiris
  password: _PBPzuhMJLiJCf9PiAY8gA
  host: wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud
  port: 26257
  database: defaultdb
  sslmode: verify-full

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# Configurações para Solid Cache, Queue e Cable
cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
