default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: tamiris
  password: _PBPzuhMJLiJCf9PiAY8gA
  host: wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud
  port: 26257
  database: defaultdb
  sslmode: require

test:
  <<: *default
  username: tamiris
  password: _PBPzuhMJLiJCf9PiAY8gA
  host: wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud
  port: 26257
  database: defaultdb
  sslmode: require

production:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'tamiris' %>
  password: <%= ENV['DB_PASSWORD'] || '_PBPzuhMJLiJCf9PiAY8gA' %>
  host: <%= ENV['DB_HOST'] || 'wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud' %>
  port: <%= ENV['DB_PORT'] || '26257' %>
  database: <%= ENV['DB_NAME'] || 'defaultdb' %>
  sslmode: require

# Configurações para Solid Cache, Queue e Cable
cache:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'tamiris' %>
  password: <%= ENV['DB_PASSWORD'] || '_PBPzuhMJLiJCf9PiAY8gA' %>
  host: <%= ENV['DB_HOST'] || 'wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud' %>
  port: <%= ENV['DB_PORT'] || '26257' %>
  database: <%= ENV['DB_NAME'] || 'defaultdb' %>
  sslmode: require

queue:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'tamiris' %>
  password: <%= ENV['DB_PASSWORD'] || '_PBPzuhMJLiJCf9PiAY8gA' %>
  host: <%= ENV['DB_HOST'] || 'wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud' %>
  port: <%= ENV['DB_PORT'] || '26257' %>
  database: <%= ENV['DB_NAME'] || 'defaultdb' %>
  sslmode: require

cable:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'tamiris' %>
  password: <%= ENV['DB_PASSWORD'] || '_PBPzuhMJLiJCf9PiAY8gA' %>
  host: <%= ENV['DB_HOST'] || 'wan-bulldog-15335.j77.aws-us-east-1.cockroachlabs.cloud' %>
  port: <%= ENV['DB_PORT'] || '26257' %>
  database: <%= ENV['DB_NAME'] || 'defaultdb' %>
  sslmode: require
